routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
//static html pages
//Route::get('/contact', 'HomeController@contact');
//Route::get('/addcontacts', 'HomeController@settings');
//Route::get('/log', 'HomeController@log');
//Route::get('/addreminder', 'HomeController@addreminder')->name('addreminder');
//Route::get('/settings', 'HomeController@settings');




Route::get('/user/login', 'Auth\RegisterController@userlogin');

//add data routes
Route::get('/insertdata', 'HomeController@adddata');
Route::get('/syncLatestRemindersToServer', 'SendRequestToServer@syncLatestRemindersToServer');
Route::get('/getLatestReminderStatusFromCloud', 'SendRequestToServer@getLatestReminderStatusFromCloud');
Route::get('/getLatestAllReminderStatusFromCloud', 'SendRequestToServer@getLatestAllReminderStatusFromCloud');

//get latest twlio logs from aws
Route::get('/getLatestReminderTwilioUpdateFromCloud', 'SendRequestToServer@getLatestReminderTwilioUpdateFromCloud');
Route::get('/syncEmailSettings', 'SendRequestToServer@syncEmailSettings');

// bulk reminder upload
Route::get('syncBulkReminder', ['as' => 'bulk.excel', 'uses' => 'BulkReminderController@addBulkReminder']);
Route::get('/calaudit-to-sns', 'ReminderController@calauditsns');
Route::get('/remindernotify', 'SendRequestToServer@remindernotify');
Route::get('/sync-staff', 'ReminderController@syncStaffDetailsToUsers');
Route::get('/updateTwilioStatusFromTheServer/{reminderId}/{twilioStatus}/{confirmdate}', 'ReminderController@updateTwilioStatusFromTheServer');
Route::get('/fetch-default-templates', 'ReminderController@fetchDefaultTemplates');

Route::get('contacts/migratecontact', 'ContactController@syncContactFromWindowsToWeb');
Route::get('/lrsreminder-to-snsreminder', 'ReminderController@syncReminderFromWindowsToWeb');
Route::get('/lrsremindertiming-to-snsremindertiming', 'ReminderController@syncReminderTimingFromWindowsToWeb');

Auth::routes();

Route::group(['middleware' => ['auth:web']], function() {

    Route::resource('users', 'UserController', ['only' => ['index', 'create', 'store', 'edit']]);
    Route::patch('users/update/{id}', ['uses' => 'UserController@update', 'as' => 'users.update']);
    Route::delete('users/delete/{id}', ['uses' => 'UserController@destroy', 'as' => 'users.destroy']);
    //contacts routes
    Route::get('contacts/getlist', ['uses' => 'ContactController@getlist', 'as' => 'datatables.data']);
    Route::resource('contacts', 'ContactController');
    Route::get('contacts/searchContact/{queryString}/{extraType?}', 'ContactController@searchForContact');
    Route::get('searchcaseno',array('as'=>'searchcaseno','uses'=>'ContactController@ajaxSearchForCaseNo'));
    Route::post('quickContactSave',array('as'=>'quickcontactsave','uses'=>'ContactController@quickContactStore'));


    //templates routes
    Route::get('mastertemplates/getlist', ['uses' => 'MasterTemplatesController@getlist', 'as' => 'templates.data']);
    Route::resource('mastertemplates', 'MasterTemplatesController');


    //reminder routes
    Route::post('/reminderAdd', ['uses' => 'ReminderController@store', 'as' => 'addReminder']);
    Route::post('/isdone', ['uses' => 'ReminderController@isdone', 'as' => 'isdone']);
    Route::post('/removecontacts', ['uses' => 'ContactController@removecontacts', 'as' => 'removecontacts']);
    Route::get('{reminderId}/reminderEdit', ['uses' => 'ReminderController@edit', 'as' => 'editReminder']);
    Route::get('{reminderId}/reminderEdit/view', ['uses' => 'ReminderController@edit', 'as' => 'editReminder']);
    Route::post('/updateReminder', ['uses' => 'ReminderController@update', 'as' => 'updateReminder']);
    Route::get('/getReminderDashboard', 'ReminderController@getRemindersList');
    Route::get('/deleteReminder', 'ReminderController@deleteReminders');
    Route::get('/addReminder/{strUserSearch?}', ['uses' => 'ReminderController@create', 'as' => 'addReminderPage']);
    Route::resource('/', 'ReminderController');



    //logs rotes
    Route::get('logs', 'TwiloLogController@index');
    Route::get('log/getlist', ['uses' => 'TwiloLogController@getlist', 'as' => 'log.data']);
    Route::get('log/addtwiliodate/{reminderId}', ['uses' => 'TwiloLogController@addtwiliodate', 'as' => 'log.addtwiliodata']);



//settings routes
    Route::get('/settings', 'SettingController@index');
    Route::post('/settings/updateLogColors', 'SettingController@updateLogColors');
    Route::post('/settings/updateTimeZone', 'SettingController@updateTimeZone');
    Route::post('/settings/updateRecallSettings', 'SettingController@updateRecallSettings');
    Route::post('/settings/updateCompanyLogoAndEmailSignature', 'SettingController@updateCompanyLogoAndEmailSignature')->name('updateCompanyLogoAndSignature');
    Route::patch('/settings/updateEmailSettings', ['uses' => 'SettingController@updateEmailSettings', 'as' => 'setting.updateemail']);
    Route::put('/settings/updateCsvSettings', 'SettingController@updateCsvSettings');
    Route::post('/settings/updateDefaultLanguageSettings', 'SettingController@updateDefaultLanguageSettings');
    Route::post('/settings/updateparalegalhandling', 'SettingController@updateparalegalhandling');
    Route::post('/settings/updatesalutation', 'SettingController@updatesalutation');
    // added by sourabh for salutation
    //Route::post('/settings/updatesyna1law', 'SettingController@updatesyna1law');
    Route::post('/settings/updatesyncsnstoa1law', 'SettingController@updatesyncsnstoa1law');    // to sync flag for updating sns reminder activity to a1law if enable.
//import csv contacts
    Route::post('import-csv', ['as' => 'import-csv-excel', 'uses' => 'ContactController@importFileIntoDB']);
//export csv contacts
    Route::get('downloadsamplefile', ['as' => 'excel.samplefile', 'uses' => 'ContactController@downloadSampleExcelFile']);
    Route::get('downloadexcelfile', ['as' => 'excel.file', 'uses' => 'ContactController@downloadExcelFile']);
//add promotional message
    Route::post('/settings/addPromotionalMessage', ['as' => 'add.promotional', 'uses' => 'SettingController@addPromotionalMessage']);
//export route
    Route::post('/settings/exportReport', ['as' => 'export.report', 'uses' => 'SettingController@exportReport']);
    Route::get('/settings/exportReport', ['uses' => 'SettingController@exportReport']);

    //users routes
    Route::get('users/getlist', ['uses' => 'UserController@getlist', 'as' => 'datatables.ur.data']);
//    Route::get('users/searchContact/{queryString}', 'UserController@searchForContact');
    
    
    // added on 23rd April 2018
    //logs rotes
    Route::get('failurelog', 'FailureController@index');
    Route::get('failurelog/getlist', ['uses' => 'FailureController@getlist', 'as' => 'failurelog.data']);
    Route::get('failurelog/addtwiliodate/{reminderId}', ['uses' => 'FailureController@addtwiliodate', 'as' => 'failurelog.addtwiliodata']);
    
    // for addressbook created by nilay
    Route::get('/addressbook', 'AddressBookController@index');
    Route::get('/addContact/{addid}/{id}', 'AddressBookController@addContact');
    Route::get('/addressbookContact/{id}', 'AddressBookController@addressbookContact');
    Route::get('/deleteContact/{addid}/{cardid}', 'AddressBookController@deleteContact');
    Route::post('/addNewBook', 'AddressBookController@addNewAddressBook');
    Route::get('/allAddressBook', 'AddressBookController@allAddressBook');
    Route::get('/deleteAddressBook/{id}', 'AddressBookController@deleteAddressBook');
    Route::get('/addressBookContactInReminder/{id}', 'AddressBookController@addressBookContactInReminder');

});

app/Addressbook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use File;
use App\Http\Controllers\SendRequestToServer;

class Addressbook extends Model {

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'address_book';
    protected $primaryKey = 'recid';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

}

app/Http/Controllers/AddressBookController.php
<?php

namespace App\Http\Controllers;

use Datatables;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use App\MasterCountry;
use App\Addressbook;
use App\AddressbookDetail;
use App\Http\Requests\ContactFormRequest;
use Illuminate\Http\Request;
use App\Contact;
use Session;
use Illuminate\Support\Facades\Redirect;
use DB;
use Excel;
use URL;
use Auth;

class AddressBookController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $data['data_list'] = Addressbook::where('status','1')->get();
        //echo '<pre>';print_r($data);exit;
        return view('addressbook.index',$data);
    }
    
    public function addressbookContact($id) {
        $data = AddressbookDetail::getContact($id);
        $arr_ids = [];
        foreach($data as $row){
            $arr_ids[] = $row->cardcode;
        }
        //print_r($arr_ids);exit;
        
        $result1 = DB::connection('mysql3')->table('card')->select(DB::raw('card.cardcode AS cardCode, casecard.caseno AS caseNo, CONCAT_WS(" ", card.salutation,card.first, card.middle, card.last) AS fullName, card.email AS email, IF(card.business <> "", card.business, IF(card.car <> "", card.car, IF(card.home <> "", card.home, IF(card2.phone1 <> "", card2.phone1, IF(card2.phone2 <> "", card2.phone2, "" ) ) ) ) ) AS phoneNumber, card.salutation AS salutation'))
                ->join('card2', 'card.firmcode', '=','card2.firmcode')
                ->join('casecard','casecard.cardcode','=','card.cardcode')
                ->whereIn('card.cardcode', $arr_ids)
                ->groupby('card.cardcode')
                ->havingRaw('fullName <> "" AND (email <> "" OR phoneNumber <> "") ')
                ->get(); 
     
        $result2 = DB::table('contact_list')->select(DB::raw('sns_contact_list.cardcode AS cardCode, sns_contact_list.case AS caseNo, CONCAT_WS(" ", sns_contact_list.salutation,sns_contact_list.firstname, sns_contact_list.middlename, sns_contact_list.lastname) AS fullName, sns_contact_list.email AS email, IF(sns_master_countries.rec_id < "", CONCAT_WS("-", sns_master_countries.countrycode, sns_contact_list.phonenumber), sns_contact_list.phonenumber) AS phoneNumber, sns_contact_list.salutation AS salutation'))
                ->leftjoin('master_countries','contact_list.country_id','=','master_countries.rec_id')
                ->whereIn('cardcode', $arr_ids)
                ->where('master_countries.isactive','A')
                ->where('master_countries.isdeleted','0')
                ->where('contact_list.isactive','A')
                ->where('contact_list.isdeleted','0')
                // ->union($result_n)
                ->get();
     
        $result = $result1->merge($result2);

        return $result;
        
    }

    public function addContact($addid, $cardcode) {
        $data = new AddressbookDetail();
        $data->addid =  $addid;
        $data->cardcode = $cardcode;
        $data->save();
        return 'success';
    }
    
    public function deleteContact($addid, $cardcode) {
        $data = AddressbookDetail::deleteContact($addid, $cardcode);
        return 'success';
    }
    
    public function addNewAddressBook(request $request){
        $data = new Addressbook();
        $data->name = $request->input('name');
        $data->created_at = date("Y-m-d H:i");
        $data->updated_at = date("Y-m-d H:i");  
        $data->save();
        return 'success';
    }
    
    public function allAddressBook(){
        $data = Addressbook::where('status','1')->get();
        return $data;
    }
    
    public function deleteAddressBook($recid){
        $data = Addressbook::where('recid', $recid)->update(['status'=>'0']);
        return $data;
    }
    
    public function addressBookContactInReminder($addid){
        
        $data = AddressbookDetail::getContact($addid);
        $arr_ids = [];
        foreach($data as $row){
            $arr_ids[] = $row->cardcode;
        }
        
        $result1 = DB::connection('mysql3')->table('card')->select(DB::raw('card.cardcode id, card.cardcode cardCode, casecard.caseno caseNo, card.salutation salutation, card.first firstName, card.middle middleName, card.last lastName, CONCAT_WS(" ", card.salutation, card.first, card.last) fullName, card.email email, IF(card.business <> "", card.business, IF(card.car <> "", card.car, IF(card.home <> "", card.home, IF(card2.phone1 <> "", card2.phone1, IF(card2.phone2 <> "", card2.phone2, "" ) ) ) ) ) phoneNumber,1 as firstnamestart,1 as middlenamestart,1 as lastnamestart, "LawwareOTS" contactType'))
                ->join('card2', 'card.firmcode', '=','card2.firmcode')
                ->join('casecard','casecard.cardcode','=','card.cardcode')
                ->whereIn('card.cardcode', $arr_ids)
                ->groupby('card.cardcode')
                ->havingRaw('fullName <> "" AND (email <> "" OR phoneNumber <> "") ')
                ->get(); 
     
        $result2 = DB::table('contact_list')->select(DB::raw('sns_contact_list.recid id, sns_contact_list.cardcode cardCode, sns_contact_list.case caseNo, sns_contact_list.salutation salutation, sns_contact_list.firstname firstName, sns_contact_list.middlename middleName, sns_contact_list.lastname lastName, CONCAT_WS(" ", sns_contact_list.salutation, sns_contact_list.firstname, sns_contact_list.lastname) fullName, sns_contact_list.email email, IF(sns_master_countries.rec_id > "", CONCAT_WS("-", sns_master_countries.countrycode, sns_contact_list.phonenumber), sns_contact_list.phonenumber) phoneNumber,1 as firstnamestart,1 as middlenamestart, 1 as lastnamestart, "SNS" contactType'))
                ->leftjoin('master_countries','contact_list.country_id','=','master_countries.rec_id')
                ->whereIn('cardcode', $arr_ids)
                ->where('master_countries.isactive','A')
                ->where('master_countries.isdeleted','0')
                ->where('contact_list.isactive','A')
                ->where('contact_list.isdeleted','0')
                // ->union($result_n)
                ->get();
        
        $result = $result1->merge($result2);

        $arrSendResponse = array(
            'statusCode' => 200,
            'data' => $result,
            'error' => 0,
            'flagMsg' => 'FETCH',
            'message' => 'Add reminder contacts fetch'
        );
        
        return $arrSendResponse;
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    

}

resources/views/addressbook/_form.blade.php
<style>
    .sl-us-css .help-block{
        position: absolute;
        bottom: -33px;
    }
</style> 
<div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="row">
                                
                                <div class="col-md-3 col-sm-3{{ $errors->has('salutation') ? ' has-error' : '' }}">
                                    {{ Form::label('salutation', 'Name') }}  
                                    {{ Form::select('salutation',array_merge([""=>'Please select salutation'],$salutation),null,['class'=>'form-control'])}}
                                    @if ($errors->has('salutation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('salutation') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                
                                

                                <div class="col-md-3 col-sm-3{{ $errors->has('firstname') ? ' has-error' : '' }}">
                                    {{ Form::label('firstname', 'First Name',['class'=>"control-label"]) }}
                                    {{ Form::text('firstname', old('firstname'), array('class' => 'form-control')) }}

                                    @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                    @endif

                                </div>
                                <div class="col-md-3 col-sm-3{{ $errors->has('middlename') ? ' has-error' : '' }}">
                                    {{ Form::label('middlename', 'Middle Name',['class'=>"control-label"]) }}
                                    {{ Form::text('middlename', old('middlename'), array('class' => 'form-control')) }}

                                    @if ($errors->has('middlename'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('middlename') }}</strong>
                                    </span>
                                    @endif

                                </div>
                                <div class="col-md-3 col-sm-3{{ $errors->has('lastname') ? ' has-error' : '' }}">
                                    {{ Form::label('lastname', 'Last Name',['class'=>"control-label"]) }}
                                    {{ Form::text('lastname', old('lastname'),['class' => 'form-control']) }}
                                    @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Phone Number</label>
                            <div class="row">
                                <div class="col-md-4 col-sm-4{{ $errors->has('country_id') ? ' has-error' : '' }}">
                                    {{ Form::label('country_id', 'Country',['class'=>"control-label"]) }}  
                                    {{ Form::select('country_id',[""=>"Please select country code"]+$countrycode,null,['class'=>'form-control'])}}
                                    @if ($errors->has('country_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('country_id') }}</strong>
                                    </span>
                                    @endif
                                </div>


                                <div class="col-md-4 col-sm-4{{ $errors->has('phonenumber') ? ' has-error' : '' }}">
                                    {{ Form::label('phonenumber', 'Number',['class'=>"control-label"]) }}
                                    {{ Form::text('phonenumber', old('phonenumber'), ['class' => 'form-control','maxlength' => 10,'minlength' => 10, 'onkeypress' => 'return isNumberic(event);']) }}
                                    @if ($errors->has('phonenumber'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phonenumber') }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="col-md-4 col-sm-4{{ $errors->has('phonetype') ? ' has-error' : '' }}">
                                    {{ Form::label('phonetype', 'Phone type') }}  
                                    {{ Form::select('phonetype',array_merge([''=>'Please enter phone type'],$phonetype),null,['class'=>'form-control'])}}
                                    @if ($errors->has('phonetype'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phonetype') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Email Address</label>
                            <div class="row">

                                <div class="col-md-8 col-sm-8{{ $errors->has('email') ? ' has-error' : '' }}">
                                    {{ Form::label('email', 'Email',['class'=>"control-label"]) }}
                                    {{ Form::text('email',null, array('class' => 'form-control')) }}

                                    @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif

                                </div>
                                <div class="col-md-4 col-sm-4{{ $errors->has('emailtype') ? ' has-error' : '' }}">
                                    {{ Form::label('emailtype', 'Email type') }}  
                                    {{ Form::select('emailtype',array_merge([''=>'Please select email type'],$emailtype),null,['class'=>'form-control'])}}
                                    @if ($errors->has('emailtype'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('emailtype') }}</strong>
                                    </span>
                                    @endif
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                 
                    <div class="sl-us-css col-md-6 col-sm-6{{ $errors->has('dob') ? ' has-error' : '' }}">
                        <div class="form-group">    
                            <label>DOB :</label>
                            <div id="input-group-datepicker" class="input-group date">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span> {{ Form::text('dob',old('dob'), ['class' => 'form-control']) }}
                              @if ($errors->has('dob'))
                        <span class="help-block">
                            <strong>{{ $errors->first('dob') }}</strong>
                        </span>
                        @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-6{{ $errors->has('zipcode') ? ' has-error' : '' }}">
                        {{ Form::label('zipcode', 'Zip Code') }}  
                          {{ Form::text('zipcode', old('zipcode'), ['class' => 'form-control','maxlength' => 10,'minlength' => 3, 'onkeypress' => 'return isNumberic(event);']) }}
                        @if ($errors->has('zipcode'))
                        <span class="help-block">
                            <strong>{{ $errors->first('zipcode') }}</strong>
                        </span>
                        @endif
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12{{ $errors->has('notes') ? ' has-error' : '' }}">
                        <div class="form-group">          
                            {{ Form::label('notes', 'Notes') }} 
                            {{ Form::textarea('notes', null, ['class' => 'form-control contactnote']) }}

                            @if ($errors->has('notes'))
                            <span class="help-block">
                                <strong>{{ $errors->first('notes') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    {!! Form::submit('Save changes', ['class' => 'btn btn-primary pull-right btn-xs m-l-10']) !!}
                   <a class="btn btn-white pull-right btn-xs" href="{{{ URL::route('contacts.index') }}}">Cancel</a>

                </div>

resources/views/addressbook/create.blade.php
@extends('layouts.app')
@section('title', 'SNS|Add Contacts')
@section('content')   

<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Add Contacts <small></small></h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content add-new-reminder-box">
            <div class="">

                {{ Form::open(['route' => 'contacts.store', 'id' => 'contact-form']) }}
                {{ csrf_field() }}
                @include("contacts/_form")
                <!-- https://laracast.blogspot.in/2016/06/laravel-ajax-crud-search-sort-and.html  -->
               
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script type="text/javascript">
    var url = "{{ route('datatables.data') }}";
</script>
<script src="{{ asset('js/webjs/contacts.js') }}"> </script>

@endsection

resources/views/addressbook/edit.blade.php
@extends('layouts.app')
@section('title', 'SNS|Edit Contacts')
@section('content')   

<div class="col-lg-12">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Edit Contacts <small></small></h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content add-new-reminder-box">
            <div class="">
                {!! Form::model($contact, [
                    'method' => 'PATCH',
                    'route' => ['contacts.update', $contact->cardcode]
                ]) !!}
               
                {{ csrf_field() }}
                <!-- https://laracast.blogspot.in/2016/06/laravel-ajax-crud-search-sort-and.html  -->
                  @include("contacts/_form")
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script type="text/javascript">
    var url = "{{ route('datatables.data') }}";
</script>
<script src="{{ asset('js/webjs/contacts.js') }}"> </script>

@endsection