routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
//static html pages
//Route::get('/contact', 'HomeController@contact');
//Route::get('/addcontacts', 'HomeController@settings');
//Route::get('/log', 'HomeController@log');
//Route::get('/addreminder', 'HomeController@addreminder')->name('addreminder');
//Route::get('/settings', 'HomeController@settings');




Route::get('/user/login', 'Auth\RegisterController@userlogin');

//add data routes
Route::get('/insertdata', 'HomeController@adddata');
Route::get('/syncLatestRemindersToServer', 'SendRequestToServer@syncLatestRemindersToServer');
Route::get('/getLatestReminderStatusFromCloud', 'SendRequestToServer@getLatestReminderStatusFromCloud');
Route::get('/getLatestAllReminderStatusFromCloud', 'SendRequestToServer@getLatestAllReminderStatusFromCloud');

//get latest twlio logs from aws
Route::get('/getLatestReminderTwilioUpdateFromCloud', 'SendRequestToServer@getLatestReminderTwilioUpdateFromCloud');
Route::get('/syncEmailSettings', 'SendRequestToServer@syncEmailSettings');

// bulk reminder upload
Route::get('syncBulkReminder', ['as' => 'bulk.excel', 'uses' => 'BulkReminderController@addBulkReminder']);
Route::get('/calaudit-to-sns', 'ReminderController@calauditsns');
Route::get('/remindernotify', 'SendRequestToServer@remindernotify');
Route::get('/sync-staff', 'ReminderController@syncStaffDetailsToUsers');
Route::get('/updateTwilioStatusFromTheServer/{reminderId}/{twilioStatus}/{confirmdate}', 'ReminderController@updateTwilioStatusFromTheServer');
Route::get('/fetch-default-templates', 'ReminderController@fetchDefaultTemplates');

Route::get('contacts/migratecontact', 'ContactController@syncContactFromWindowsToWeb');
Route::get('/lrsreminder-to-snsreminder', 'ReminderController@syncReminderFromWindowsToWeb');
Route::get('/lrsremindertiming-to-snsremindertiming', 'ReminderController@syncReminderTimingFromWindowsToWeb');

Auth::routes();

Route::group(['middleware' => ['auth:web']], function() {

    Route::resource('users', 'UserController', ['only' => ['index', 'create', 'store', 'edit']]);
    Route::patch('users/update/{id}', ['uses' => 'UserController@update', 'as' => 'users.update']);
    Route::delete('users/delete/{id}', ['uses' => 'UserController@destroy', 'as' => 'users.destroy']);
    //contacts routes
    Route::get('contacts/getlist', ['uses' => 'ContactController@getlist', 'as' => 'datatables.data']);
    Route::resource('contacts', 'ContactController');
    Route::get('contacts/searchContact/{queryString}/{extraType?}', 'ContactController@searchForContact');
    Route::get('searchcaseno',array('as'=>'searchcaseno','uses'=>'ContactController@ajaxSearchForCaseNo'));
    Route::post('quickContactSave',array('as'=>'quickcontactsave','uses'=>'ContactController@quickContactStore'));


    //templates routes
    Route::get('mastertemplates/getlist', ['uses' => 'MasterTemplatesController@getlist', 'as' => 'templates.data']);
    Route::resource('mastertemplates', 'MasterTemplatesController');


    //reminder routes
    Route::post('/reminderAdd', ['uses' => 'ReminderController@store', 'as' => 'addReminder']);
    Route::post('/isdone', ['uses' => 'ReminderController@isdone', 'as' => 'isdone']);
    Route::post('/removecontacts', ['uses' => 'ContactController@removecontacts', 'as' => 'removecontacts']);
    Route::get('{reminderId}/reminderEdit', ['uses' => 'ReminderController@edit', 'as' => 'editReminder']);
    Route::get('{reminderId}/reminderEdit/view', ['uses' => 'ReminderController@edit', 'as' => 'editReminder']);
    Route::post('/updateReminder', ['uses' => 'ReminderController@update', 'as' => 'updateReminder']);
    Route::get('/getReminderDashboard', 'ReminderController@getRemindersList');
    Route::get('/deleteReminder', 'ReminderController@deleteReminders');
    Route::get('/addReminder/{strUserSearch?}', ['uses' => 'ReminderController@create', 'as' => 'addReminderPage']);
    Route::resource('/', 'ReminderController');



    //logs rotes
    Route::get('logs', 'TwiloLogController@index');
    Route::get('log/getlist', ['uses' => 'TwiloLogController@getlist', 'as' => 'log.data']);
    Route::get('log/addtwiliodate/{reminderId}', ['uses' => 'TwiloLogController@addtwiliodate', 'as' => 'log.addtwiliodata']);



//settings routes
    Route::get('/settings', 'SettingController@index');
    Route::post('/settings/updateLogColors', 'SettingController@updateLogColors');
    Route::post('/settings/updateTimeZone', 'SettingController@updateTimeZone');
    Route::post('/settings/updateRecallSettings', 'SettingController@updateRecallSettings');
    Route::post('/settings/updateCompanyLogoAndEmailSignature', 'SettingController@updateCompanyLogoAndEmailSignature')->name('updateCompanyLogoAndSignature');
    Route::patch('/settings/updateEmailSettings', ['uses' => 'SettingController@updateEmailSettings', 'as' => 'setting.updateemail']);
    Route::put('/settings/updateCsvSettings', 'SettingController@updateCsvSettings');
    Route::post('/settings/updateDefaultLanguageSettings', 'SettingController@updateDefaultLanguageSettings');
    Route::post('/settings/updateparalegalhandling', 'SettingController@updateparalegalhandling');
    Route::post('/settings/updatesalutation', 'SettingController@updatesalutation');
    // added by sourabh for salutation
    //Route::post('/settings/updatesyna1law', 'SettingController@updatesyna1law');
    Route::post('/settings/updatesyncsnstoa1law', 'SettingController@updatesyncsnstoa1law');    // to sync flag for updating sns reminder activity to a1law if enable.
//import csv contacts
    Route::post('import-csv', ['as' => 'import-csv-excel', 'uses' => 'ContactController@importFileIntoDB']);
//export csv contacts
    Route::get('downloadsamplefile', ['as' => 'excel.samplefile', 'uses' => 'ContactController@downloadSampleExcelFile']);
    Route::get('downloadexcelfile', ['as' => 'excel.file', 'uses' => 'ContactController@downloadExcelFile']);
//add promotional message
    Route::post('/settings/addPromotionalMessage', ['as' => 'add.promotional', 'uses' => 'SettingController@addPromotionalMessage']);
//export route
    Route::post('/settings/exportReport', ['as' => 'export.report', 'uses' => 'SettingController@exportReport']);
    Route::get('/settings/exportReport', ['uses' => 'SettingController@exportReport']);

    //users routes
    Route::get('users/getlist', ['uses' => 'UserController@getlist', 'as' => 'datatables.ur.data']);
//    Route::get('users/searchContact/{queryString}', 'UserController@searchForContact');
    
    
    // added on 23rd April 2018
    //logs rotes
    Route::get('failurelog', 'FailureController@index');
    Route::get('failurelog/getlist', ['uses' => 'FailureController@getlist', 'as' => 'failurelog.data']);
    Route::get('failurelog/addtwiliodate/{reminderId}', ['uses' => 'FailureController@addtwiliodate', 'as' => 'failurelog.addtwiliodata']);
    
    // for addressbook created by nilay
    Route::get('/addressbook', 'AddressBookController@index');
    Route::get('/addContact/{addid}/{id}', 'AddressBookController@addContact');
    Route::get('/addressbookContact/{id}', 'AddressBookController@addressbookContact');
    Route::get('/deleteContact/{addid}/{cardid}', 'AddressBookController@deleteContact');
    Route::post('/addNewBook', 'AddressBookController@addNewAddressBook');
    Route::get('/allAddressBook', 'AddressBookController@allAddressBook');
    Route::get('/deleteAddressBook/{id}', 'AddressBookController@deleteAddressBook');
    Route::get('/addressBookContactInReminder/{id}', 'AddressBookController@addressBookContactInReminder');

});

app/MasterTemplates.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class MasterTemplates extends Model
{
   /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table='master_reminder_template';
    
      /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'recid';

    const CREATED_AT = 'createddate';
    const UPDATED_AT = 'updateddate';
    const IS_DELETED = 1;
    const IS_NOT_DELETED = 0;
    const IS_ACTIVE = 'A';
    const IS_NOT_ACTIVE = 'I';
    
    public $fields;
    
    protected $fillable = ['title', 'purpose', 'bodyemail', 'bodysms', 'language', 'flagsms',
        'smstimingid', 'flagcall', 'calltimingid', 'flagemail', 'emailtimingid', 'created_at', 'updated_at', 'isreschedule' ,'isdisable','iscallback',
        'firmcode', 'cardcode', 'country_id'];

    

   
    
       protected static function setemptyvalue($request,$mastertemplates)
    {
         // echo '<pre>'; print_r($mastertemplates);exit;
       if(!isset($request['calltimingid']) && empty($request['calltimingid'])){
           $mastertemplates->calltimingid='';
       }if(!isset($request['smstimingid']) && empty($request['smstimingid'])){
           $mastertemplates->smstimingid='';
       }if(!isset($request['emailtimingid']) && empty($request['emailtimingid'])){
           $mastertemplates->emailtimingid='';
       }if(!isset($request['isreschedule']) && empty($request['isreschedule'])){
           $mastertemplates->isreschedule='N';
       }if(!isset($request['isdisable']) && empty($request['isdisable'])){
           $mastertemplates->isdisable='N';
       }if(!isset($request['iscallback']) && empty($request['iscallback'])){
           $mastertemplates->iscallback='N';
       }
       $mastertemplates->save();
     }
    
    
    
       public function scopeActive($query)
    {
        return $query->where('isactive', 'A')->where('isdeleted', 0);
    }
    
    /**
     * Set the templates's sms timing id.
     *
     * @param  string  $value
     * @return void
     */
     public function setBodyemailAttribute($value) {
 
       $this->attributes['bodyemail'] =  strip_tags($value);
      
    }
    /**
     * Set the templates's sms timing id.
     *
     * @param  string  $value
     * @return void
     */
     public function setSmstimingidAttribute($value) {

       $this->attributes['smstimingid'] =  (!empty($value))?implode(',',$value):"";
         $this->attributes['flagsms']=(!empty($value))?'Y':'N';
    }
    
     /**
     * Set the templates's email timing id.
     *
     * @param  string  $value
     * @return void
     */
    
     public function setEmailtimingidAttribute($value) {
         
        $this->attributes['emailtimingid'] =(!empty($value))?implode(',',$value):"";
         $this->attributes['flagemail']=(!empty($value))?'Y':'N';
    }
    
      /**
     * Set the templates's call timing id.
     *
     * @param  string  $value
     * @return void
     */
    
    public function setCalltimingidAttribute($value) {
         
        $this->attributes['calltimingid'] = (!empty($value))?implode(',',$value):"";
         $this->attributes['flagcall']=(!empty($value))?'Y':'N';
    }
    
     /**
     * Get the templates's sms timing id.
     *
     * @param  string  $value
     * @return string
     */
    public function getSmstimingidAttribute($value)
    {
        return explode(',',$value);
    }
     /**
     * Get the templates's email timing id.
     *
     * @param  string  $value
     * @return string
     */
    public function getEmailtimingidAttribute($value)
    {
        return explode(',',$value);
    }
    
     /**
     *  Get the templates's call timing id.
     *
     * @param  string  $value
     * @return string
     */
    public function getCalltimingidAttribute($value)
    {
        return explode(',',$value);
    }
    
     
    
}

app/Http/Controllers/MasterTemplatesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\MasterTemplates;
use Datatables;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use App\Http\Requests\MasterTemplatesRequest;
use Session;
use Illuminate\Support\Facades\Redirect;
use DB;
use Carbon\Carbon;

class MasterTemplatesController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return Redirect::to('settings');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $flagcolumn = ['SMS', 'CALL', 'EMAIL'];
        $language = \App\TwilioLanguage::getlanguage();
        $fields = \App\ReminderFields::getfields();
        $slots = \App\ReminderSlots::getslots();
        $column = [0, 1, 2, 3];
        $datatitle='Create';
        return view('mastertemplates.create')->with(['language' => $language, 'fields' => $fields, 'slots' => $slots,
                    'column' => $column, 'flagcolumn' => $flagcolumn, 'datatitle'=>$datatitle]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MasterTemplatesRequest $request) {
        DB::beginTransaction();
        try {
            // process the store
            $input = $request->all();
            $contact = MasterTemplates::create($input);
        } catch (\Exception $e) {
            DB::rollback();
            //throw $e;
            Session::flash('message', 'Oops something went wrong');
            return Redirect::to('settings');
        }
        // If we reach here, then// data is valid and working.//
        DB::commit();
        // redirect
        Session::flash('message', 'Templates created successfully ');
        return Redirect::to('settings');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $mastertemplates = MasterTemplates::find($id);
        $flagcolumn = ['SMS', 'CALL', 'EMAIL'];
        $language = \App\TwilioLanguage::getlanguage();
        $fields = \App\ReminderFields::getfields();
        $slots = \App\ReminderSlots::getslots();
        $column = [0, 1, 2, 3];
            $datatitle='Edit';
        return view('mastertemplates.edit')->with(['language' => $language, 'fields' => $fields, 'slots' => $slots,
                    'column' => $column, 'flagcolumn' => $flagcolumn, 'mastertemplates' => $mastertemplates,
            'datatitle'=>$datatitle]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MasterTemplatesRequest $mastertemplaterequest, $id) {
        DB::beginTransaction();
        try {

            $request = $mastertemplaterequest->all();
            // process the store
            $mastertemplates = MasterTemplates::find($id);
            MasterTemplates::setemptyvalue($request, $mastertemplates);
            $mastertemplates->update($request);
        } catch (\Exception $e) {
            DB::rollback();
            // throw $e;
            Session::flash('message', 'Oops something went wrong');
            return Redirect::to('settings');
        }
        // If we reach here, then// data is valid and working.//
        DB::commit();
        // redirect
        Session::flash('message', 'Templates updated successfully ');
        return Redirect::to('settings');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $contacts = MasterTemplates::find($id);
        $contacts->isdeleted = MasterTemplates::IS_DELETED;
        $contacts->save();
    }

    /**
     * get the list from master templates table.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function getlist(Request $request) {
        $request = $request->all();
        // get all the contacts
        $templates = MasterTemplates::select(['recid', 'title', 'purpose', 'createddate', 'bodyemail'])->active();
        $datatables = Datatables::of($templates)
                ->editColumn('bodyemail', function ($templates) {
                    return strlen($templates->bodyemail) > 50 ? substr($templates->bodyemail, 0, 50) . "..." : $templates->bodyemail;
                })->editColumn('createddate', function ($user) {
                       return $user->createddate->format('d/m/Y');
                })
                ->filterColumn('createddate', function ($query, $keyword) {
            $query->whereRaw("DATE_FORMAT(createddate,'%d/%m/%Y') like ?", ["%$keyword%"]);
        });

        // Global search function

        return $datatables->make(true);
    }

}

resources/views/mastertemplates/_form.blade.php
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>{{ $datatitle }} Appointment Template</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content add-new-reminder-box">
            <div class="">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-6s">
                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            {{ Form::label('title', 'Title') }}  
                            {{ Form::text('title', null, array('class' => 'form-control')) }}  
                            @if ($errors->has('title'))
                            <span class="help-block">
                                <strong>{{ $errors->first('title') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <div class="form-group{{ $errors->has('purpose') ? ' has-error' : '' }}">
                            {{ Form::label('purpose', 'Appointment Type') }}  
                            {{ Form::text('purpose', null, array('class' => 'form-control')) }}  
                            @if ($errors->has('purpose'))
                            <span class="help-block">
                                <strong>{{ $errors->first('purpose') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>


                    <div class="col-md-4 col-sm-6 col-xs-6">
                        <div class="form-group{{ $errors->has('language') ? ' has-error' : '' }}">
                            {{ Form::label('language', 'Language') }}  
                            {{ Form::select('language',[""=>"Please select language"]+$language,null,['class'=>'form-control'])}}
                            @if ($errors->has('language'))
                            <span class="help-block">
                                <strong>{{ $errors->first('language') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>   

                </div>
                <div class="row">
                    <div class="col-md-12">

                        <div class="form-group note-editable-group{{ $errors->has('bodyemail') ? ' has-error' : '' }}">
                            {{ Form::label('bodyemail', 'Event Body') }}  
                            {{ Form::textarea('bodyemail', null, ['class' => 'form-control']) }}
                            @if ($errors->has('bodyemail'))
                            <span class="help-block">
                                <strong>{{ $errors->first('bodyemail') }}</strong>
                            </span>
                            @endif
                        </div>


                    </div>
                </div>

                <div class="row add-new-checkbox">


                    <div class="col-md-4 col-sm-4 col-xs-6 addfields">
                        <div class="form-group{{ $errors->has('fields') ? ' has-error' : '' }}">
                            {{ Form::label('fields', 'Insert Field') }}  
                            {{ Form::select('fields',[""=>'Please select fields']+$fields,null,['class'=>'form-control'])}}
                            @if ($errors->has('fields'))
                            <span class="help-block">
                                <strong>{{ $errors->first('fields') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div> 


                    <div class="col-md-6 col-sm-8 col-xs-6">
                        <div class="m-b-20"></div>
                        <?php
                        $checkeddiabled = ((isset($mastertemplates) && $mastertemplates->isreschedule == 'Y')  ? 1 : 0); ?>                        
                        {{ Form::checkbox('isreschedule','Y',$checkeddiabled) }}
                        <span>Disable Reschedule.</span><br>
                         <?php
                        $isdisable = ((isset($mastertemplates) && $mastertemplates->isdisable == 'Y')  ? 1 : 0); ?>
                        {{ Form::checkbox('isdisable','Y',$isdisable) }}
                        <span>Disable Cancel.</span><br>
                         <?php
                        $iscallback = ((isset($mastertemplates) && $mastertemplates->iscallback == 'Y')  ? 1 : 0); ?>
                        {{ Form::checkbox('iscallback','Y',$iscallback) }}
                        <span>Disable Callback.</span>
                    </div> 


                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Participant Details</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="row add-new-checkbox reminder-types-table">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th style="width: 120px">Reminder Types</th>
                                    @foreach ($flagcolumn as $key=>$value)

                                    <th>
                                        <div class="i-checks">
                                            
                                                <?php if($key==0){
                                                  $checked= ((isset($mastertemplates) && $mastertemplates->flagsms =='Y')?1:0);
                                                }
                                                elseif($key==1) {
                                                   $checked=((isset($mastertemplates) && $mastertemplates->flagcall=='Y')?1:0);
                                                }
                                                elseif($key==2) {
                                                   $checked= ((isset($mastertemplates) && $mastertemplates->flagemail =='Y')?1:0);
                                                }?>
                                            <label> {{ Form::checkbox($value,$value,$checked,['class'=>'select-colcheckboxhead','data'=>'dataid'.$key]) }}<span> {{ $value}}</span></label>
                                        </div>
                                    </th>
                                    @endforeach
                                </tr>
                            </thead>
                            <tbody>


                                @foreach ($slots as $key=>$value)
                                <tr>  
                                    @foreach ($column as $columns)
                                    <td>
                                        <div class="i-checks">
                                            <label>
                                                <?php
                                               
                                                $checkedsms = (isset($mastertemplates))?in_array($value['slotId'], $mastertemplates->smstimingid): '';
                                                $checkedcall = (isset($mastertemplates))? in_array($value['slotId'], $mastertemplates->calltimingid):'';
                                                $checkedemail = (isset($mastertemplates))? in_array($value['slotId'], $mastertemplates->emailtimingid):'';
                                                $checkedrow = ($checkedsms == 1 && $checkedcall == 1 && $checkedemail == 1)??'';
                                                
                                                ?>

                                                @if($columns==1)

                                                {{ Form::checkbox('smstimingid[]',$value['slotId'],$checkedsms,['class'=>'select-colcheckbox','data'=>'dataid0']) }}<span> {{$value['slots'] }}</span>

                                                @elseif($columns==2)
                                                <?php /* @if($value['slots'] != "Immediate") */?>
                                                {{ Form::checkbox('calltimingid[]',$value['slotId'],$checkedcall,['class'=>'select-colcheckbox','data'=>'dataid1']) }}<span> {{$value['slots'] }}</span>
                                                <?php /* @endif */?>
                                                @elseif($columns==3)
                                                {{ Form::checkbox('emailtimingid[]',$value['slotId'],$checkedemail,['class'=>'select-colcheckbox','data'=>'dataid2']) }}<span> {{$value['slots'] }}</span>
                                                @else


                                                {{ Form::checkbox('timingid[]',$value['slotId'],$checkedrow,['class'=>'select-rowcheckbox']) }}

                                                @endif
                                            </label>
                                        </div>
                                    </td>
                                    @endforeach
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>                         
            <div class="participant-details-box">
                <div class="row">                                        
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="submit-event-btn">

                            <a class="btn btn-danger btn-sm" href="{{{ URL::route('mastertemplates.index') }}}">Cancel</a>

                            {!! Form::submit('Save', ['class' => 'btn btn-primary import-appointment-btn btn-sm']) !!}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/mastertemplates/create.blade.php
@extends('layouts.app')
@section('title', 'SNS | Add Templates')
@section('content')   

<div class="wrapper wrapper-content animated fadeInRight add-template">
    <div class="row">
        
                {{ Form::open(['route' => 'mastertemplates.store', 'id' => 'contact-form']) }}
                {{ csrf_field() }}
                     @include("mastertemplates/_form")
                <!-- https://laracast.blogspot.in/2016/06/laravel-ajax-crud-search-sort-and.html  -->
               
                {{ Form::close() }}

  

    </div>
</div>

@endsection

@section('scripts')

<script type="text/javascript">
    var url = "{{ route('templates.data') }}";
</script>
<script src="{{ asset('js/webjs/mastertemplates.js') }}"></script>
@endsection

resources/views/mastertemplates/edit.blade.php
@extends('layouts.app')
@section('title', 'SNS | Edit Templates')
@section('content')   


<div class="wrapper wrapper-content animated fadeInRight add-template">
    <div class="row">
        
                {!! Form::model($mastertemplates, [
                    'method' => 'PATCH',
                    'route' => ['mastertemplates.update', $mastertemplates->recid],
                   
                ]) !!}
               <input type="hidden" name="_token" value="{{ csrf_token() }}">
                {{ csrf_field() }}
                <!-- https://laracast.blogspot.in/2016/06/laravel-ajax-crud-search-sort-and.html  -->
                   @include("mastertemplates/_form")
                {{ Form::close() }}

            </div>
        </div>


@endsection

@section('scripts')

<script type="text/javascript">
    var url = "{{ route('templates.data') }}";
</script>
<script src="{{ asset('js/webjs/mastertemplates.js') }}"></script>
@endsection